<html>
	<head>
	<!--favicon code generated by realfavicongenerator.net -->
		<link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
		<link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
		<link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
		<link rel="manifest" href="site.webmanifest">
		<link rel="mask-icon" href="safari-pinned-tab.svg" color="#5bbad5">
		<meta name="msapplication-TileColor" content="#da532c">
		<meta name="theme-color" content="#ffffff">
		<style>
		body {
			font-family: sans-serif;
		}
		table {
			text-align: center;
			border: 1px dotted gray;
			border-collapse: collapse;
		}
		tr,td {
			border: 1px dotted gray;
		}
		button {
			width: 100%;
			user-select: none;
		}
		</style>
		<title>Make your own soundboards!</title>
		<script>
			//Get sound num will need to be called on the page first in order to get the number of HTMLAudioElements that need to be created
			var audioelems;
			function init_audio() {
				audioelems = document.getElementsByTagName("audio");
			}
			function play_sound(num) {
				audioelems[num].play();
			}
		</script>
		<?php
			$sounds = glob("sounds/*/*.{mp3,wav}", GLOB_BRACE); //GLOB_BRACE lets you match multiple filename extensions with the curlies
			$soundnum = count($sounds);
			
			function make_html_id($filename) {
				$soundid = str_replace(' ', '', $filename);
				$soundid = str_replace('.mp3', '', $soundid);
				$soundid = str_replace('.wav', '', $soundid);
				$soundid = strtolower($soundid);//Makes sure id doesn't have any weird characters from filename(spaces,extensions,uppercase)
				return $soundid;
			}
			echo "<style type='text/css'>";
			for($elemite=0;$elemite<=$soundnum;$elemite++){ 
				if(strpos($sounds[$elemite], ".mp3") != false){
					$soundname = basename($sounds[$elemite], ".mp3");
					$soundid = make_html_id($soundname);
					$randomcolor = strval(bin2hex(random_bytes(3)));//Generate the 3 random color bytes then convert them to hexadecimal then to string
					echo "#{$soundid}{background-color:#{$randomcolor};}\n";
				}
				if(strpos($sounds[$elemite], ".wav") != false){
					$soundname = basename($sounds[$elemite], ".wav");
					$soundid = make_html_id($soundname);
					$randomcolor = strval(bin2hex(random_bytes(3)));
					echo "#{$soundid}{background-color:#{$randomcolor};}\n";
				}
			}
			echo "</style>";
		?>
	</head>
	<body onload="init_audio()">
		<?php
		$tablecols = 10;//30 columns seems like a good amount for most computers
		$sounds = glob("sounds/*/*.{mp3,wav}", GLOB_BRACE); //GLOB_BRACE lets you match multiple filename extensions with the curlies
		$soundnum = count($sounds);
		$tablerows = floor($soundnum/$tablecols);//Makes sure we always have enough spots in the table
		echo $tablerows;
		echo "<table>";
		$elemite = 0;//Outside iterator
		while($elemite<=999) {
			for($rowite=1;$rowite<=$tablerows;$rowite++) {
				echo "<tr>";
				for($colite=1;$colite<=$tablecols;$colite++) {
					
					echo "<td>";
					if(strpos($sounds[$elemite], ".mp3") != false){//Give the proper MIME type for each audio file
						$soundname = basename($sounds[$elemite], ".mp3");
						$soundid = make_html_id($soundname);
						
						//Audio tag with source tag
						echo "<audio><source src='{$sounds[$elemite]}' type='audio/mp3'></audio>";
						//Button
						echo "<button type='button' class='soundbutton' id='{$soundid}' onclick='play_sound({$elemite})'>{$soundname}</button>";
						
					}
					elseif(strpos($sounds[$elemite], ".wav") != false){
						$soundname = basename($sounds[$elemite], ".wav");
						$soundid = make_html_id($soundname);
						//Audio tag with source tag
						echo "<audio><source src='{$sounds[$elemite]}' type='audio/wav'></audio>";
						//Button
						echo "<button type='button' class='soundbutton' id='{$soundid}' onclick='play_sound({$elemite})'>{$soundname}</button>";
						
					}
					echo "</td>";
					$elemite++;
				}
				
			}
			echo "</tr>";
			
		}
		echo "</table>";
		?>
	<h1>Create your own soundboards!</h1>
	<h2>This is a test of the general concept and layout without the backend yet.</h2>
	</body>
</html>